
name: Linux Test

on: 
  pull_request:
    types: [opened,synchronize]
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: File tree
      run: tree

    - name: Install Google Test
      run: |
        git clone https://github.com/google/googletest.git -b v1.14.0
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        cd ../
        sudo cp -r ./googlemock/include/gmock /usr/local/include/gmock
        sudo cp -r ./googletest/include/gtest /usr/local/include/gtest
        sudo cp ./build/lib/*.a /usr/local/lib/
        cd ../
    
    - name: Build Test Code
      run: |
        cd test
        mkdir build
        cd build
        cmake ..
        make
    
    - name: Run Tests
      run: |
        cd test/build
        echo =================================================================
        echo is_option
        echo =================================================================

        ./is_option

        echo =================================================================
        echo options_check
        echo =================================================================

        ./options_check

        echo =================================================================
        echo fill_zero
        echo =================================================================

        ./fill_zero
