
name: Windows Test

on: 
  pull_request:
    types: [opened,synchronize]
  push:
    branches: [main]

jobs:
    build:
        runs-on: windows-latest

        steps:
          -  uses: actions/checkout@v4

          - name: Install Google Test
            shell: powershell
            run: |
              git clone https://github.com/google/googletest.git -b v1.14.0
              cd googletest
              mkdir build
              cd build
              cmake ..
              make
              dir
