
name: Windows Test

on: 
  pull_request:
    types: [opened,synchronize]
  push:
    branches: [main]

jobs:
    build:
        runs-on: windows-latest

        steps:
          -  uses: actions/checkout@v4

          - name: Build Test
            shell: powershell
            run: |
              cd test
              mkdir build
              cd build
              cmake ..

          - name: Run Test
            shell: powershell
            run: |
              ./tmp
